### ISSUE TITLE
optimize the size of docker image

### ISSUE THREAD

**Issue by maoxuner** [Jamesits/docker-dst-server#21]
Currently, the image has a size of about 1GB. It is hard to download. (I'm in China)
I think it will be better if server initial scripts run after container's first launch.

Maybe we can put the following scripts in `entrypoint.sh`. Check dst server contents and decide whether to initalize.
```
# install Don't Starve Together server
RUN mkdir -p /opt/dst_server \
    && steamcmd +runscript /opt/steamcmd_scripts/install_dst_server_initial \
    && rm -rf /root/Steam /root/.steam
```

**Comment by Jamesits** [comment]
Myself being a developer in P.R. China, I understand it is a pain to download large files from Docker Hub. But there are some drawbacks on the changes you proposed:

* The image will lose its ability to be deployed offline
* Every time a container is created, the whold game server will be redownloaded (assume no further action is taken to persist the game server)
* If we remove the DST server executable from the container, then this container is effectively a SteamCMD container rather than a DST server container

Given the fact that Steam have CDN deployed in P.R. China and that this container itself does not need frequent update, is building the image locally an option to you? If not, I think we can create another container image for SteamCMD and rebase this image on the top of that one.

**Comment by maoxuner** [comment]
I think building the image locally is the best choice for me.

Maintaining a standalone SteamCMD image takes extra effort. Less time on server, more joy in game.

**Comment by Jamesits** [comment]
Thank you. I'm closing this issue now, if you have more thoughts feel free to re-open it.

**Comment by maoxuner** [comment]
I've found a standalone steamcmd image [steamcmd/steamcmd](https://hub.docker.com/r/steamcmd/steamcmd). Will it be better to rebase dst image on top of this steamcmd image.
Since the server code will be updated on every launch, it seems moving initial scripts to entrypoint isn't hard to accept.

**Comment by Jamesits** [comment]
Try the new `steamcmd-rebase-slim` tag.

**Comment by maoxuner** [comment]
Hi, Jamesits. Thank you for your great job.

I have tried `steamcmd-rebase` tag using default cluster configuration on my mbp with docker for mac version `19.03.8`. 
```bash
docker run --name dst -v $PWD/data:/data -p 127.0.0.1:10999-11000:10999-11000 -d jamesits/dst-server:steamcmd-rebase
```
After I filled in cluster_token and restarted container, I got the following error.
```
Updating server...
Error on line 48; RET 1.
```
I tried to run entrypoint scripts manually and got this.
```
Unable to determine CPU Frequency. Try defining CPU_MHZ.
```
I've met this problem when I tried to rebase your image to steamcmd yesterday.
Referring [Steam is installed but won't open.](https://www.reddit.com/r/Crostini/comments/9dev4p/steam_is_installed_but_wont_open/) page, I tried to pass envar CPU_MHZ=3100 and it worked.
```bash
docker run --name dst -v $PWD/data:/data -p 127.0.0.1:10999-11000:10999-11000 -e CPU_MHZ=3100 -d jamesits/dst-server:steamcmd-rebase
```
But I don't know what happened.
Could this envar be set automatically? What's the difference between ubuntu package steamcmd and `steamcmd_linux.tar.gz`?

**Comment by Jamesits** [comment]
### CPU_MHZ problem

I did some basic analysis on the `steamcmd` binary. It tries to acquire cpu frequency via the 3 methods in sequence:
* The `CPU_MHZ` env var
* `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`
* `/proc/cpuinfo`

If all the methods failed, it prints the error message you see. 

I'm not even sure if it actually used this value. The value is simply put into some struct containing other information about the processor and seems to be only used in determining how much threads to launch during parallel operations. 

### Could this envar be set automatically? 

I don't think there is a reliable way to detect CPU freq in the docker container because of the nature of virtualization. Also it works well on my Linux VM without setting `CPU_MHZ`.

### What's the difference between ubuntu package steamcmd and steamcmd_linux.tar.gz

I'm not sure what Ubuntu's package team did to that package, and I'm not familiar with debian packaging process. There package scripts are [here](https://packages.ubuntu.com/source/eoan/steamcmd) if you have interest.

**Comment by maoxuner** [comment]
I've tried `latest` tag, and the containered terminated with error `CPU_MHZ` too. It must have something to do with docker for mac.

Ubuntu package steamcmd and steamcmd_linux.tar.gz are almost the same.
```bash
tree steamcmd-0\~20180105.orig
steamcmd-0~20180105.orig
├── steamcmd
└── steamcmd.sh
md5sum steamcmd-0\~20180105.orig/steamcmd
063eaedf842d7454d7db16079ba36a4f  steamcmd-0~20180105.orig/steamcmd
md5sum steamcmd-0\~20180105.orig/steamcmd.sh 
689d34308f1cf6f6fc1345649af13114  steamcmd-0~20180105.orig/steamcmd.sh

tree steamcmd_linux
steamcmd_linux
├── linux32
│   ├── crashhandler.so
│   ├── libstdc++.so.6
│   ├── steamcmd
│   └── steamerrorreporter
└── steamcmd.sh
md5sum steamcmd_linux/linux32/steamcmd 
063eaedf842d7454d7db16079ba36a4f  steamcmd_linux/linux32/steamcmd
md5sum steamcmd_linux/steamcmd.sh 
689d34308f1cf6f6fc1345649af13114  steamcmd_linux/steamcmd.sh
```

---

Another steamcmd image [cm2network/steamcmd](https://hub.docker.com/r/cm2network/steamcmd) which is mentioned in [SteamCMD#Docker | Valve Developer Commiunity](https://developer.valvesoftware.com/wiki/SteamCMD#Docker) and is based on `debian:buster-slim`. It is slimmer than steamcmd/steamcmd too. I think it will be a better choice.

If you are going to rebase your image on top of cm2network/steamcmd. You'd better use the `root` tag as base because supervisor should run as root. Also, cm2network/steamcmd already has an unprevilaged user `steam`. DST can run with user `steam` too.

**Comment by Jamesits** [comment]
Tried to adopt to `cm2network/steamcmd` but in many cases it gave me `Error! App '343050' state is 0x602 after update job.`. Still investgating.

**Comment by Jamesits** [comment]
#27 need some manual conflict resolution, I'll proceed tomorrow.

**Comment by Jamesits** [comment]
Please try the new `vanilla-slim` or `steamcmd-rebase-slim` tags. They are both ~60MiB. I don't think I have the time to maintain multiple branches so I updated the build files on the master branch to support multiple `FROM` images.

**Comment by maoxuner** [comment]
OK. Thank you for your work.

**Comment by maoxuner** [comment]
I've tried latest `vanilla-slim`,`steamcmd-rebase` and `steamcmd-rebase-slim`. Everything is ok.

**Comment by Jamesits** [comment]
Nice, thank you for your feedback!
