### ISSUE TITLE
Abnormal language of game characters

### ISSUE THREAD

**Issue by Moac1129** [Jamesits/docker-dst-server#36]
Hello, I am a gamer from China. I found a small problem. In the game, the character only speaks English. This happens even if I set the language of the game client to Chinese. I hope the game characters speak Chinese, how to solve this problem

**Comment by theAkito** [comment]
According to the [Steam Page](https://store.steampowered.com/app/322330/Dont_Starve_Together/), the game has only support for English audio.

Therefore, the solution in your case would be translating and recording all dialogue options yourself.

Once that is done, you have to patch the game, so the new recording are included and may be used in-game.
However, since patching the game is probably illegal, you have to team up with Klei Entertainment and show them the recordings.
If they agree to include them, they have to patch the game, release an update and then you have to download and install the update, before you can actually use the Chinese audio in-game.

Perhaps there is a way to add a mod that changes the audio, so you could just create a mod with your recordings, but I don't know about such way. Perhaps you can research further on that, if you are still interested in fixing your issue.

**Comment by Jamesits** [comment]
The game is not written by me; I only wrote some scripts to help you launch a multiplayer server. If you want any enhancements to the game itself, I think it is more appropriate to ask on [the official forum](https://forums.kleientertainment.com/forums/forum/73-dont-starve-together/).
